name: DeployToGitHubPages

env:
  PROJECT_NAME: ProduceWithPandas
  PUBLISH_DIR: ProduceWithPandas/bin/Release/net6.0/publish/wwwroot
  # Include subfolders if needed

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Setup .NET
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    - name: Publish app
      run: |
        cd ${{ env.PROJECT_NAME }}
        dotnet publish -c Release
      # You can use cd before if your project is in a subfolder

    - name: Rewrite base href
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
      with:
        html_path: ${{ env.PUBLISH_DIR }}/index.html
        base_href: /${{ env.PROJECT_NAME }}/

    - name: GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v1.5.1
      with:
        target_branch: gh-pages
        build_dir: ${{ env.PUBLISH_DIR }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}